# @name GET_/api/usuarios
GET http://localhost:8080/api/usuarios


###

# @name get_by_id
GET http://localhost:8080/api/usuarios/1

###

# @name post_usuario
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
  "nome": "teste",
  "email": "teste@email.com",
  "senha": "123456"
}

###

# @name put_usuario
PUT http://localhost:8080/api/usuarios/1
Content-Type: application/json

{
  "nome": "testezim",
  "email": "teste@email.com",
  "senha": "123456"
}


###

# @name delete_by_id
DELETE http://localhost:8080/api/usuarios/1
